version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_PROMETHEUS_AUTH_TYPE: public
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data

  create-minio-bucket:
    image: minio/mc:latest
    depends_on:
      - minio
    volumes:
      - ./minio/init.sh:/init.sh:ro
    entrypoint: ["/bin/sh", "/init.sh"]
    restart: on-failure

  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    depends_on:
      - minio
    environment:
      JMX_PORT: "9999"                     # включает удалённый коннектор
      RMI_HOSTNAME: "localhost"
      KAFKA_OPTS: >-
        -Djava.rmi.server.hostname=localhost
        -javaagent:/opt/jmx/jmx_prometheus_javaagent-1.0.1.jar=7071:/opt/jmx/jmx-exporter-config.yml
    ports:
      - "9092:9092"   # Kafka
      - "7071:7071"   # jmx_exporter HTTP
      - "9999:9999"   # JMX/RMI для JConsole
    volumes:
      - ./kafka/data:/var/lib/kafka/data
      - ./kafka/server.properties:/opt/kafka/config/server.properties:ro
      - ./kafka/jmx:/opt/jmx:ro
      - ./kafka/aiven/core-1.1.1:/opt/kafka/aiven/core-1.1.1:ro
      - ./kafka/aiven/s3-1.1.1:/opt/kafka/aiven/s3-1.1.1:ro
    command: >
      bash -lc '
      if [ ! -f /var/lib/kafka/data/meta.properties ]; then
        /opt/kafka/bin/kafka-storage.sh format -t ${KAFKA_CLUSTER_ID:-$(/opt/kafka/bin/kafka-storage.sh random-uuid)} -c /opt/kafka/config/server.properties;
      fi;
      exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
      '

  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    restart: unless-stopped
    pid: host
    volumes:
      - /:/host:ro
    command:
      - '--path.rootfs=/host'
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    depends_on:
      - kafka
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:10.4.4
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
