{
 "title": "Kafka Broker Overview",
 "description": "Comprehensive Grafana dashboard for monitoring Kafka brokers (KRaft).",
 "tags": [
  "kafka",
  "jmx",
  "broker",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate,_cluster)"
    }
   },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate{_cluster=\"$cluster\"},_environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Controller",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_value{metric=\"ActiveControllerCount\", _cluster=\"$cluster\", _environment=\"$environment\"} > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Broker Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_leadercount{_cluster=\"$cluster\", _environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_controller_value{metric=\"GlobalTopicCount\", _cluster=\"$cluster\", _environment=\"$environment\"})",
     "legendFormat": "{{jmx_version}}"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_value{metric=\"GlobalPartitionCount\",_cluster=\"$cluster\", _environment=\"$environment\"})",
     "legendFormat": "{{jmx_version}}"
    }
   ]
  },
  {
   "title": "Total Data Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_size{_cluster=~\"$cluster\", _environment=\"$environment\"})",
     "legendFormat": "{{jmx_version}}"
    }
   ]
  },
  {
   "title": "JMX Info",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(max(jmx_exporter_build_info{_cluster=\"$cluster\",_environment=\"$environment\"}) by (version), \"jmx_version\", \"$1\", \"version\", \"(.+)\")",
     "legendFormat": "{{jmx_version}}"
    }
   ]
  },
  {
   "title": "JMX Scrape Duration (Max)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(jmx_scrape_duration_seconds{_cluster=\"$cluster\", _environment=\"$environment\"}[$__range])) by (instance)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Total Req/s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_network_requestmetrics_requestspersec_oneminuterate{_cluster=\"$cluster\",_environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk & Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Offline Log Directories",
   "type": "timeseries",
   "description": "Displays the number of offline log directories in Kafka brokers. A value greater than zero indicates potential disk failures or mount issues.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_offlinelogdirectorycount{ _cluster=\"$cluster\", _environment=\"$environment\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log Flush Rate & Time (ms)",
   "type": "timeseries",
   "description": "Displays the log flush rate and flush time in Kafka brokers. High flush time may indicate disk I/O bottlenecks, while low flush rate may increase data loss risk.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(kafka_logflushstats_logflushrateandtimems_oneminuterate{_cluster=\"$cluster\", _environment=\"$environment\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log Cleaner Max Clean Time",
   "type": "timeseries",
   "description": "Displays the longest time taken by Kafka's log cleaner process to clean a log segment. High values may indicate disk I/O bottlenecks or inefficient log segment configurations.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kafka_logcleaner_max_clean_time_secs{_cluster=\"$cluster\", _environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Topic & Partition Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Partition Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "kafka_partitioncount{_cluster=~\"$cluster\", _environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leader Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "kafka_leadercount{_cluster=~\"$cluster\", _environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "timeseries",
   "description": "The number of under-replicated partitions (| ISR | < | current replicas |). Replicas that are added as part of a reassignment will not count toward this value. Alert if the value is greater than 0.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_underreplicatedpartitions{_cluster=~\"$cluster\", _environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(kafka_underreplicatedpartitions{_cluster=~\"$cluster\", _environment=\"$environment\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Under Min. ISR Partitions",
   "type": "timeseries",
   "description": "The number of partitions whose in-sync replicas count is less than minIsr.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_underminisrpartitioncount{_cluster=~\"$cluster\", _environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(kafka_underminisrpartitioncount{_cluster=~\"$cluster\", _environment=\"$environment\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Authentication & Handshake", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Kafka Failed Authentication Rate",
   "type": "timeseries",
   "description": "Displays the rate of failed authentication attempts in Kafka brokers. High values may indicate incorrect client configurations, expired credentials, or network issues.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (instance,listener) (kafka_server_socketservermetrics_failed_authentication_rate{_cluster=\"$cluster\", _environment=\"$environment\"})",
     "legendFormat": "{{listener}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Authentication Time (Avg)",
   "type": "timeseries",
   "description": "Displays the average time (in nanoseconds) taken for authentication in Kafka brokers. High values may indicate slow authentication mechanisms, overloaded brokers, or network latency issues.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems_mean{request=\"SaslHandshake\",_cluster=\"$cluster\", _environment=\"$environment\"}",
     "legendFormat": "{{request}} - {{instance}} - {{network_processor}}"
    }
   ]
  },
  {
   "title": "Kafka Request Size (Avg)",
   "type": "timeseries",
   "description": "Displays the average request size (in bytes) received by Kafka brokers. High values may indicate large batch sizes or increased network traffic, potentially leading to performance bottlenecks.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_request_size_avg{_cluster=\"$cluster\", _environment=\"$environment\"}) by (instance, listener)",
     "legendFormat": "{{listener}} - {{instance}}"
    }
   ]
  },
  { "title": "Traffic (In & Out)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Top 5 Consume Rate",
   "type": "timeseries",
   "description": "Displays the rate of outgoing bytes per second from Kafka brokers. A high value may indicate increased consumer traffic or possible broker overload.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_broker_bytes_rate{direction=\"BytesOutPerSec\", _cluster=~\"$cluster\", _environment=\"$environment\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Top 5 Produce Rate",
   "type": "timeseries",
   "description": "Displays the rate of incoming bytes per second to the Kafka brokers. A high value may indicate increased producer traffic or possible broker overload.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(5, sum by (topic) (kafka_broker_bytes_rate{direction=\"BytesInPerSec\", _cluster=~\"$cluster\", _environment=\"$environment\",topic!=\"\"}))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Top 5 Messages Produce Count Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5,\n  sum by (topic) (\n    kafka_broker_messages_in_rate{\n      _cluster=~\"$cluster\",\n      _environment=\"$environment\",\n      topic!=\"\"\n    }\n  )\n)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Broker Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kafka_broker_bytes_rate{direction=\"BytesInPerSec\", _cluster=~\"$cluster\", _environment=\"$environment\",topic!=\"\"})",
     "legendFormat": "Produce"
    },
    {
     "expr": "sum(kafka_broker_bytes_rate{direction=\"BytesOutPerSec\", _cluster=~\"$cluster\", _environment=\"$environment\",topic!=\"\"})",
     "legendFormat": "Consume"
    }
   ]
  },
  {
   "title": "Total Producer Requests Per Second (by Topic)",
   "type": "timeseries",
   "description": "Displays the total number of producer requests received per second. A high value indicates increased producer traffic, which may impact broker performance if it exceeds processing capacity.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kafka_server_brokertopicmetrics_totalproducerequestspersec_oneminuterate{_cluster=\"$cluster\", _environment=\"$environment\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total Fetch Requests Per Second (by Topic)",
   "type": "timeseries",
   "description": "Displays the total number of fetch requests received per second. High values may indicate increased consumer traffic, overloaded brokers, or inefficient partition distribution.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_totalfetchrequestspersec_oneminuterate{_cluster=\"$cluster\", _environment=\"$environment\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Req/s (Total)",
   "type": "timeseries",
   "description": "In general, this is the best place to look to know if your brokers are potentially being strained. Intermittent spikes in this value could indicate that individual clients are causing problems in the way they’re making requests. ",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (request) (\n  kafka_network_requestmetrics_requestspersec_oneminuterate{\n    request=~\"Produce|FetchConsumer|FetchFollower\"\n  }\n)",
     "legendFormat": "{{instance}} {{request}}"
    }
   ]
  },
  {
   "title": "Req/s (For each request type)",
   "type": "timeseries",
   "description": "Becomes slow with all hosts, hence select only one host. API 'version' field ignored. ",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (request) (rate(kafka_network_requestmetrics_requestspersec_total{_cluster=\"$cluster\",_environment=\"$environment\"}[10m])) > 0",
     "legendFormat": "{{request}}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Kafka Log Fetch Latency (p99.9)",
   "type": "timeseries",
   "description": "Displays the 99.9th percentile latency of log fetch operations in Kafka brokers. High values indicate slow disk reads, overloaded brokers, or excessive consumer request traffic.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_localtimems_99p{request=\"Fetch\", _cluster=\"$cluster\", _environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fetcher(Follower) Lag",
   "type": "timeseries",
   "description": "The lag in number of messages per follower replica. This is useful to know if the replica is slow or has stopped replicating from the leader and if the associated brokers need to be removed from the In-Sync Replicas list.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_fetcherlagmetrics_consumerlag{_cluster=\"$cluster\", _environment=\"$environment\",_role=\"broker\"} > 0) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka ISR Shrinks Per Second",
   "type": "timeseries",
   "description": "Displays the rate at which replicas are removed from the ISR (In-Sync Replicas) set. A high value indicates potential replication issues or follower replicas falling behind the leader.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_replicamanager_isrshrinkspersec{_cluster=\"$cluster\", _environment=\"$environment\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed ISR Updates Per Second",
   "type": "timeseries",
   "description": "Displays the number of failed ISR (In-Sync Replicas) updates per second. High values indicate replication issues, network delays, or configuration problems with min.insync.replicas.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_replicamanager_failedisrupdatespersec{_cluster=\"$cluster\", _environment=\"$environment\"}[5m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Follower Fetch Requests Per Second (by Topic)",
   "type": "timeseries",
   "description": "Displays the total number of fetch requests received from follower brokers per second. A high value may indicate frequent replication fetches, network congestion, or slow replication.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestspersec_oneminuterate{request=\"Fetch\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch from Follower Requests Per Second",
   "type": "timeseries",
   "description": "Displays the number of fetch requests received from follower brokers per second. A high value may indicate frequent replication fetches, network congestion, or slow replication.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 50 },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems_99p{request=\"FetchFollower\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication Bytes In Per Second",
   "type": "timeseries",
   "description": "Displays the incoming byte rate for replication in Kafka brokers. High values may indicate active replication processes, increased broker load, or network congestion.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_broker_bytes_rate{direction=\"ReplicationBytesInPerSec\",_cluster=\"$cluster\", _environment=\"$environment\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication Bytes Out Per Second",
   "type": "timeseries",
   "description": "Displays the outgoing byte rate for replication in Kafka brokers. High values may indicate active replication processes, increased broker load, or network congestion.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_broker_bytes_rate{direction=\"ReplicationBytesOutPerSec\",_cluster=\"$cluster\", _environment=\"$environment\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Follower - LocalTimeMS",
   "type": "timeseries",
   "description": "In most cases, a high value can imply slow local storage or the storage is a bottleneck. One should also investigate LogFlushRateAndTimeMs to know how long page flushes are taking, which will also indicate a slow disk. In the case of FetchFollower requests, time spent in LocalTimeMs can be the result of a ZooKeeper write to change the ISR.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_localtimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"FetchFollower\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Follower - RemoteTimeMS",
   "type": "timeseries",
   "description": "A high value can imply a slow network connection. For fetch request, if the remote time is high, it could be that there is not enough data to give in a fetch response. This can happen when the consumer or replica is caught up and there is no new incoming data. If this is the case, remote time will be close to the max wait time, which is normal. Max wait time is configured via replica.fetch.wait.max.ms and fetch.max.wait.ms.\n",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_remotetimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"FetchFollower\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Follower - TotalTimeMS",
   "type": "timeseries",
   "description": "A high value can imply there aren't enough IO threads or the CPU is a bottleneck, or the request queue isn't large enough. The request queue size should match the number of connections.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"FetchFollower\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Follower - RequestQueueTimeMS",
   "type": "timeseries",
   "description": "A high value can imply there aren't enough IO threads or the CPU is a bottleneck, or the request queue isn't large enough. The request queue size should match the number of connections.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestqueuetimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"FetchFollower\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Follower - ResponseQueueTimeMS",
   "type": "timeseries",
   "description": "A high value can imply there aren't enough network threads or the network cant dequeue responses quickly enough, causing back pressure in the response queue.\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"FetchFollower\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Follower - ResponseSendTimeMS",
   "type": "timeseries",
   "description": "A high value can imply the zero-copy from disk to the network is slow, or the network is the bottleneck because the network cant dequeue responses of the TCP socket as quickly as theyre being created. If the network buffer gets full, Kafka will block.\n",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"FetchFollower\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Producer Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Failed Produce Requests (Per Sec)",
   "type": "timeseries",
   "description": "Displays the number of failed producer requests per second in Kafka. High values may indicate broker-side errors, authentication issues, or topic unavailability.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_brokertopicmetrics_failedproducerequestspersec_oneminuterate{_cluster=~\"$cluster\", _environment=\"$environment\"}[1m]))",
     "legendFormat": "Total Failed Producer Requests"
    }
   ]
  },
  {
   "title": "Kafka Log Append Latency (p99.9)",
   "type": "timeseries",
   "description": "Displays the 99.9th percentile latency of log appends in Kafka brokers. High values indicate slow disk writes, broker overload, or excessive producer request traffic.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(request) (kafka_network_requestmetrics_localtimems_99p{_cluster=\"$cluster\", _environment=\"$environment\"})",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Producer - TotalTimeMS",
   "type": "timeseries",
   "description": "A high value can imply there aren't enough IO threads or the CPU is a bottleneck, or the request queue isn't large enough. The request queue size should match the number of connections.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"Produce\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Producer - ResponseQueueTimeMS",
   "type": "timeseries",
   "description": "A high value can imply there aren't enough network threads or the network cant dequeue responses quickly enough, causing back pressure in the response queue.\n",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"Produce\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Producer - LocalTimeMS",
   "type": "timeseries",
   "description": "In most cases, a high value can imply slow local storage or the storage is a bottleneck. One should also investigate LogFlushRateAndTimeMs to know how long page flushes are taking, which will also indicate a slow disk. In the case of FetchFollower requests, time spent in LocalTimeMs can be the result of a ZooKeeper write to change the ISR.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_localtimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"Produce\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Producer - RemoteTimeMS",
   "type": "timeseries",
   "description": "A high value can imply a slow network connection. For fetch request, if the remote time is high, it could be that there is not enough data to give in a fetch response. This can happen when the consumer or replica is caught up and there is no new incoming data. If this is the case, remote time will be close to the max wait time, which is normal. Max wait time is configured via replica.fetch.wait.max.ms and fetch.max.wait.ms.\n",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_remotetimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"Produce\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Producer - RequestQueueTimeMS",
   "type": "timeseries",
   "description": "A high value can imply there aren't enough IO threads or the CPU is a bottleneck, or the request queue isn't large enough. The request queue size should match the number of connections.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestqueuetimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"Produce\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Producer - ResponseQueueTimeMS",
   "type": "timeseries",
   "description": "A high value can imply the zero-copy from disk to the network is slow, or the network is the bottleneck because the network cant dequeue responses of the TCP socket as quickly as theyre being created. If the network buffer gets full, Kafka will block.\n",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"Produce\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Consumer Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Failed Fetch Requests (Per Sec)",
   "type": "timeseries",
   "description": "Displays the number of failed fetch requests per second in Kafka. High values may indicate consumer or broker-side errors, authentication issues, or topic unavailability.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_failedfetchrequestspersec_oneminuterate{_cluster=~\"$cluster\", _environment=\"$environment\"} * 60)",
     "legendFormat": "Total Failed Fetch Requests"
    }
   ]
  },
  {
   "title": "Consumer - TotalTimeMS",
   "type": "timeseries",
   "description": "A high value can imply there aren't enough IO threads or the CPU is a bottleneck, or the request queue isn't large enough. The request queue size should match the number of connections.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems_99p{request=\"FetchConsumer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumer - RequestQueueTimeMS",
   "type": "timeseries",
   "description": "A high value can imply there aren't enough IO threads or the CPU is a bottleneck, or the request queue isn't large enough. The request queue size should match the number of connections.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestqueuetimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"FetchConsumer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumer - LocalTimeMS",
   "type": "timeseries",
   "description": "In most cases, a high value can imply slow local storage or the storage is a bottleneck. One should also investigate LogFlushRateAndTimeMs to know how long page flushes are taking, which will also indicate a slow disk. In the case of FetchFollower requests, time spent in LocalTimeMs can be the result of a ZooKeeper write to change the ISR.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_localtimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"FetchConsumer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumer - RemoteTimeMS",
   "type": "timeseries",
   "description": "A high value can imply a slow network connection. For fetch request, if the remote time is high, it could be that there is not enough data to give in a fetch response. This can happen when the consumer or replica is caught up and there is no new incoming data. If this is the case, remote time will be close to the max wait time, which is normal. Max wait time is configured via replica.fetch.wait.max.ms and fetch.max.wait.ms.\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_remotetimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"FetchConsumer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumer - ResponseQueueTimeMS",
   "type": "timeseries",
   "description": "A high value can imply there aren't enough network threads or the network cant dequeue responses quickly enough, causing back pressure in the response queue.\n",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"FetchConsumer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumer - ResponseSendTimeMS",
   "type": "timeseries",
   "description": "A high value can imply the zero-copy from disk to the network is slow, or the network is the bottleneck because the network cant dequeue responses of the TCP socket as quickly as theyre being created. If the network buffer gets full, Kafka will block.\n",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems_99p{_cluster=\"$cluster\",_environment=\"$environment\",request=\"FetchConsumer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Offline Partitions",
   "type": "timeseries",
   "description": "The number of partitions that don’t have an active leader and are therefore not writable or readable. Alert if value is greater than 0.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "kafka_controller_value{metric=\"OfflinePartitionsCount\",_cluster=~\"$cluster\", _environment=~\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fenced Broker Count",
   "type": "timeseries",
   "description": "In KRaft mode, the number of fenced, but registered brokers as observed by this controller. This metric is always 0 in ZooKeeper mode.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 102 },
   "targets": [
    {
     "expr": "kafka_controller_value{metric=\"FencedBrokerCount\",_cluster=~\"$cluster\", _environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stray Partitions Count",
   "type": "timeseries",
   "description": "Number of partitions being replicated unexpectedly based on current cluster metadata. Should remain at 0 in a healthy state.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "kafka_underreplicatedpartitions{_cluster=~\"$cluster\", _environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Preferred Replica Imbalance Count",
   "type": "timeseries",
   "description": "\nThe count of topic partitions for which the leader is not the preferred leader.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 102 },
   "targets": [
    {
     "expr": "kafka_controller_value{metric=\"PreferredReplicaImbalanceCount\", _cluster=~\"$cluster\", _environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{_cluster=\"$cluster\",_environment=\"$environment\",device!=\"lo\",job=\"node\"}[5m])*8",
     "legendFormat": "recv {{instance}} - {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{_cluster=\"$cluster\",_environment=\"$environment\",device!=\"lo\",job=\"node\"}[5m])*8",
     "legendFormat": "trans {{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{_cluster=\"$cluster\", _environment=\"$environment\", device!~'rootfs', mountpoint=~\"/kafka-data|/data|/\"} * 100) / node_filesystem_size_bytes{_cluster=\"$cluster\", _environment=\"$environment\",  device!~'rootfs', mountpoint=~\"/kafka-data|/data|/\"})",
     "legendFormat": "{{instance}} mount: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{_cluster=\"$cluster\",_environment=\"$environment\"} * 100) / node_memory_MemTotal_bytes{_cluster=\"$cluster\",_environment=\"$environment\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Server Load Avg",
   "type": "table",
   "description": "Displays the 1/5/15-minute Linux load average of Kafka brokers. High values may indicate sustained CPU overload or resource contention over time.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(node_load1{_cluster=~\"$cluster\", _environment=~\"$environment\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance)(node_load5{_cluster=~\"$cluster\", _environment=~\"$environment\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance)(node_load15{_cluster=~\"$cluster\", _environment=~\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM & GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "description": "This graph is a percentage from 0 to 100 of how busy the I/O threads––also known as the Request Handler Threads––are. The metric is key in alerting on how loaded a broker is. ",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_used_bytes{_cluster=~\"$cluster\", _environment=\"$environment\"})",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "jvm_memory_max_bytes{_cluster=~\"$cluster\", _environment=\"$environment\"}",
     "legendFormat": "{{instance}} max"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "description": "This graph is a percentage from 0 to 100 of how busy the I/O threads––also known as the Request Handler Threads––are. The metric is key in alerting on how loaded a broker is. ",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{_cluster=~\"$cluster\", _environment=\"$environment\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM GC Collection Count",
   "type": "timeseries",
   "description": "Displays the total number of garbage collection (GC) events in the JVM. A high rate may indicate frequent garbage collection, which can impact application performance.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "sum(jvm_gc_collection_seconds_count{_cluster=\"$cluster\", _environment=\"$environment\"}) by (gc, instance)",
     "legendFormat": "{{gc}} - {{instance}}"
    }
   ]
  },
  {
   "title": "JVM Threads by State",
   "type": "bargauge",
   "description": "Displays the number of JVM threads in different states (RUNNABLE, TIMED_WAITING, BLOCKED, etc.). High values in BLOCKED or TIMED_WAITING states may indicate contention issues or performance bottlenecks.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 125 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(jvm_threads_state{_cluster=\"$cluster\", _environment=\"$environment\"}) by (state, instance) > 0)",
     "legendFormat": "{{state}} - {{instance}}"
    }
   ]
  },
  {
   "title": "JVM Current Threads",
   "type": "timeseries",
   "description": "Displays the current number of active threads in the JVM. A high value may indicate excessive concurrency, inefficient thread management, or potential memory leaks.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 132 },
   "targets": [
    {
     "expr": "max(jvm_threads_current{_cluster=\"$cluster\", _environment=\"$environment\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Network & Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "Request Queue Size",
   "type": "timeseries",
   "description": "A higher count means that the queue is congested, so it’s better to have a lower value. In conjunction with NetworkProcessorAvgIdlePercent, you can get a good idea of how busy the full Kafka request pipeline is.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_requestqueuesize{_cluster=~\"$cluster\", _environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Queue Size",
   "type": "timeseries",
   "description": "Displays the size of the Kafka response queue. A consistently high value may indicate slow network response times, overloaded brokers, or high client request traffic.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_responsequeuesize{_cluster=~\"$cluster\", _environment=\"$environment\",processor!~\".+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka I/O Time (Avg)",
   "type": "timeseries",
   "description": "Displays the average time (in nanoseconds) spent on I/O operations in Kafka brokers. High values may indicate disk or network bottlenecks, leading to potential performance degradation.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (instance,listener) (kafka_server_socketservermetrics_io_time_ns_avg{_cluster=\"$cluster\", _environment=\"$environment\"})",
     "legendFormat": "{{instance}} - ({{listener}})"
    }
   ]
  },
  {
   "title": "Kafka I/O Wait Time (Avg)",
   "type": "timeseries",
   "description": "Displays the average time (in nanoseconds) spent waiting for I/O operations in Kafka brokers. High values may indicate disk or network bottlenecks, leading to performance degradation.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum (kafka_server_socketservermetrics_io_wait_time_ns_avg{_cluster=\"$cluster\", _environment=\"$environment\"}) by (listener,instance)",
     "legendFormat": "{{listener}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Network I/O Rate",
   "type": "timeseries",
   "description": "Displays the total network I/O rate in Kafka brokers. High values may indicate increased producer and consumer activity, leading to potential network bottlenecks.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_network_io_rate{_cluster=\"$cluster\", _environment=\"$environment\"}) by (instance,listener)",
     "legendFormat": "{{listener}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Request Queue Time p99 ms",
   "type": "timeseries",
   "description": "Displays the number of pending requests time in Kafka's socket server pipeline. A high value may indicate overloaded brokers, insufficient request handlers, or network bottlenecks.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 147 },
   "targets": [
    {
     "expr": "sum by (request) (kafka_network_requestmetrics_requestqueuetimems_99p)",
     "legendFormat": "{{request}} - {{instance}}"
    }
   ]
  },
  { "title": "Thread & Request Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "NetworkProcessor Usage",
   "type": "timeseries",
   "description": "This metric describes the percentage of time that your network threads are busy. Should be below 70%. ",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1-kafka_network_socketserver_networkprocessoravgidlepercent{_cluster=~\"$cluster\", _environment=\"$environment\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Errors & Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 } },
  {
   "title": "Network Request Errors Per Second",
   "type": "timeseries",
   "description": "Displays the number of request errors per second in Kafka. A high value may indicate authentication failures, client misconfigurations, or broker issues affecting request handling.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_network_requestmetrics_errorspersec_oneminuterate{_cluster=\"$cluster\", _environment=\"$environment\", error!=\"NONE\"}) by (instance, request, error)",
     "legendFormat": "{{request}} ({{error}}) - {{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Rejected Per Sec",
   "type": "timeseries",
   "description": "Displays the amount of data (in bytes) rejected per second by Kafka brokers. High values indicate issues with message size limits, replica fetch limits, or authorization failures.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_broker_bytes_rate{direction=\"BytesRejectedPerSec\", _cluster=\"$cluster\",_environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}