{
 "title": "Diploma metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "S3 API Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (api) (increase(minio_s3_requests_total{}[$__range]))",
     "legendFormat": "{{server,api}}"
    },
    {
     "expr": "sum(increase(minio_s3_requests_total{api=~\"putobject|newmultipartupload|putobjectpart|completemultipartupload\"}[$__range]))",
     "legendFormat": "PUT ops {{server,api}}"
    },
    {
     "expr": "sum(increase(minio_s3_requests_total{api=~\"getobject|headobject\"}[$__range]))",
     "legendFormat": "GET ops {{server,api}}"
    }
   ]
  },
  {
   "title": "Объём данных в MinIO",
   "type": "timeseries",
   "description": "общий размер байт",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "minio_bucket_usage_total_bytes", "legendFormat": "{{bucket}}" }
   ]
  },
  {
   "title": "Размер локальных логов для топика",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_log_size)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Общее количество объектов в бакете",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_bucket_usage_object_total",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Скорость поступления/чтения данных",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "kafka_broker_bytes_rate", "legendFormat": "{{topic}} {{direction}}" }
   ]
  }
 ]
}