python3 generate_experiments_updated_jmxfix.py \
  --out EXPERIMENTS_LHS_LAB.md \
  --bootstrap-servers localhost:19092 \
  --topic-bootstrap-servers localhost:9092 \
  --kafka-container kafka \
  --partitions 12 \
  --replication-factor 1 \
  --remote-storage-enable true \
  --broker-k-upl-key remote.log.manager.thread.pool.size \
  --load-profile write-heavy \
  --duration-sec 3600 \
  --producer-script producer_load.py \
  --consumer-script consumer_load.py \
  --clean-script clean.sh \
  --consumer-mode steady-state \
  --warmup-sec 900 \
  --measure-sec 2700 \
  --slo-sec 0.2