startDelaySeconds: 0
whitelistObjectNames:
  - "*:*"

rules:
  # ---------- JVM (Унифицировано) ----------
  # jvm_memory_used_bytes{area="heap|nonheap"}
  - pattern: 'java\.lang<type=Memory><(Heap|NonHeap)MemoryUsage>'
    name: jvm_memory_used_bytes
    value: '$$["used"]'
    labels:
      area: "$1"
    type: GAUGE

  # jvm_threads_count
  - pattern: 'java\.lang<type=Threading><>ThreadCount'
    name: jvm_threads_count
    type: GAUGE

  # ---------- Broker traffic (OneMinuteRate) ----------
  # BytesIn/BytesOut total по брокеру
  - pattern: 'kafka\.server<type=BrokerTopicMetrics, name=(BytesInPerSec|BytesOutPerSec)><>OneMinuteRate'
    name: kafka_broker_bytes_rate
    labels:
      direction: "$1"
    type: GAUGE

  # TODO
  # MessagesInPerSec per-topic
  - pattern: 'kafka\.server<type=BrokerTopicMetrics, name=MessagesInPerSec, topic=([a-zA-Z0-9\._-]+)><>OneMinuteRate'
    name: kafka_broker_messages_in_rate
    labels:
      topic: "$1"
    type: GAUGE

  # ---------- Quorum Controller (Унифицировано) ----------
  # Ловит все метрики Value из kafka.controller (QuorumControllerMetrics, KafkaController)
  - pattern: 'kafka\.controller<type=[^,]+(?:, node-id=([0-9]+))?(?:,.*)?, name=([A-Za-z0-9_.-]+)><>Value'
    name: kafka_controller_value
    labels:
      node_id: "$1"
      metric: "$2"
    type: GAUGE

  # ---------- Универсальный fallback для всех kafka.* c Value (Обязательно без дополнительных групп!) ----------
  # Отсюда приедут: UnderReplicatedPartitions, OfflinePartitionsCount, NetworkProcessorAvgIdlePercent и т.д.
  - pattern: 'kafka\.[^<]+<type=[^,>]+(?:,[^>]+)?, name=([A-Za-z0-9_.-]+)><>Value'
    name: kafka_$1
    type: GAUGE
