process.roles=controller,broker
node.id=1


listeners=INTERNAL://:9092,EXTERNAL://:19092,CONTROLLER://:9093,RLMM://:9094
advertised.listeners=INTERNAL://kafka:9092,EXTERNAL://localhost:19092,RLMM://127.0.0.1:9094
listener.security.protocol.map=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,RLMM:PLAINTEXT

remote.log.metadata.manager.listener.name=RLMM
inter.broker.listener.name=INTERNAL

controller.listener.names=CONTROLLER
controller.quorum.voters=1@kafka:9093

log.dirs=/var/lib/kafka/data
num.partitions=3
auto.create.topics.enable=true

# Tiered Storage
remote.log.storage.system.enable=true
remote.log.metadata.manager.class.name=org.apache.kafka.server.log.remote.metadata.storage.TopicBasedRemoteLogMetadataManager
#remote.log.metadata.manager.listener.name=PLAINTEXT
remote.log.metadata.topic.replication.factor=1
rlmm.config.remote.log.metadata.topic.replication.factor=1
rlmm.config.remote.log.metadata.topic.num.partitions=1
remote.log.metadata.topic.num.partitions=1
remote.log.manager.task.interval.ms=5000
log.retention.check.interval.ms=5000

remote.log.storage.manager.class.name=io.aiven.kafka.tieredstorage.RemoteStorageManager
remote.log.storage.manager.class.path=/opt/kafka/aiven/core-1.1.1/*:/opt/kafka/aiven/s3-1.1.1/*
remote.log.storage.manager.impl.prefix=rsm.config.
remote.log.metadata.manager.impl.prefix=rlmm.config.
remote.log.manager.thread.pool.size=1

rsm.config.storage.backend.class=io.aiven.kafka.tieredstorage.storage.s3.S3Storage
rsm.config.storage.s3.bucket.name=kafka-remote
rsm.config.storage.s3.region=us-east-1
rsm.config.storage.s3.endpoint.url=http://minio:9000
rsm.config.storage.s3.path.style.access.enabled=true

rsm.config.storage.aws.access.key.id=minioadmin
rsm.config.storage.aws.secret.access.key=minioadmin123
rsm.config.chunk.size=4194304
