process.roles=controller,broker
node.id=1
listeners=PLAINTEXT://:9092,CONTROLLER://:9093
advertised.listeners=PLAINTEXT://kafka:9092
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
inter.broker.listener.name=PLAINTEXT
controller.quorum.voters=1@kafka:9093

log.dirs=/var/lib/kafka/data
num.partitions=3
auto.create.topics.enable=true

# Tiered Storage
remote.log.storage.system.enable=true
remote.log.metadata.manager.class.name=org.apache.kafka.server.log.remote.metadata.storage.TopicBasedRemoteLogMetadataManager
remote.log.metadata.manager.listener.name=PLAINTEXT
rlmm.config.remote.log.metadata.topic.replication.factor=1
remote.log.manager.task.interval.ms=5000
log.retention.check.interval.ms=5000

remote.log.storage.manager.class.name=io.aiven.kafka.tieredstorage.RemoteStorageManager
remote.log.storage.manager.class.path=/opt/kafka/aiven/core-1.1.1/*:/opt/kafka/aiven/s3-1.1.1/*
remote.log.storage.manager.impl.prefix=rsm.config.

rsm.config.storage.backend.class=io.aiven.kafka.tieredstorage.storage.s3.S3Storage
rsm.config.storage.s3.bucket.name=kafka-remote
rsm.config.storage.s3.endpoint=http://minio:9000
rsm.config.storage.s3.region=us-east-1
rsm.config.storage.s3.path.style.access=true
rsm.config.storage.s3.access.key=minioadmin
rsm.config.storage.s3.secret.key=minioadmin123
rsm.config.chunk.size=4194304
