# ???????? tiered storage
remote.log.storage.system.enable=true

# RLMM (?????????? ? ???????)
remote.log.metadata.manager.class.name=org.apache.kafka.server.log.remote.metadata.storage.TopicBasedRemoteLogMetadataManager
remote.log.metadata.manager.listener.name=PLAINTEXT
rlmm.config.remote.log.metadata.topic.replication.factor=1
rlmm.config.remote.log.metadata.topic.num.partitions=1

# Aiven Remote Storage Manager
remote.log.storage.manager.class.name=io.aiven.kafka.tieredstorage.RemoteStorageManager
# ?????: classpath ?? JAR'?? ???????
remote.log.storage.manager.class.path=/opt/kafka/aiven/core-1.1.1:/opt/kafka/aiven/s3-1.1.1
# ????? ? ? "/*", ???? ??????? ??????????, ??? ????? jar'?
# remote.log.storage.manager.class.path=/opt/kafka/aiven/core-1.1.1/*:/opt/kafka/aiven/s3-1.1.1/*

# ??????? ??? ???????? RSM
remote.log.storage.manager.impl.prefix=rsm.config.

# S3 (MinIO)
rsm.config.storage.backend.class=io.aiven.kafka.tieredstorage.storage.s3.S3Storage
rsm.config.storage.s3.bucket.name=kafka-remote
rsm.config.storage.s3.endpoint=http://minio:9000
rsm.config.storage.s3.region=us-east-1
rsm.config.storage.s3.path.style.access=true
rsm.config.storage.s3.access.key=minioadmin
rsm.config.storage.s3.secret.key=minioadmin123

# ??? (???????????; ???? ? ???? ??? ?????????????)
rsm.config.fetch.chunk.cache.class=io.aiven.kafka.tieredstorage.fetch.cache.DiskChunkCache
rsm.config.fetch.chunk.cache.path=/var/lib/kafka/cache
rsm.config.fetch.chunk.cache.size=17179869184
